<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerVthvxuw\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerVthvxuw/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerVthvxuw.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerVthvxuw\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerVthvxuw\appDevDebugProjectContainer(array(
    'container.build_hash' => 'Vthvxuw',
    'container.build_id' => 'e50acdbf',
    'container.build_time' => 1518795336,
));
