<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXyhg0bp\appTestDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXyhg0bp/appTestDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerXyhg0bp.legacy');

    return;
}

if (!\class_exists(appTestDebugProjectContainer::class, false)) {
    \class_alias(\ContainerXyhg0bp\appTestDebugProjectContainer::class, appTestDebugProjectContainer::class, false);
}

return new \ContainerXyhg0bp\appTestDebugProjectContainer(array(
    'container.build_hash' => 'Xyhg0bp',
    'container.build_id' => '2f508dff',
    'container.build_time' => 1518981551,
));
