<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerVpszz9x\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerVpszz9x/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerVpszz9x.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerVpszz9x\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerVpszz9x\appDevDebugProjectContainer(array(
    'container.build_hash' => 'Vpszz9x',
    'container.build_id' => 'a78c0ba9',
    'container.build_time' => 1522581221,
));
