<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerYznclnw\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerYznclnw/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerYznclnw.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerYznclnw\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerYznclnw\appDevDebugProjectContainer(array(
    'container.build_hash' => 'Yznclnw',
    'container.build_id' => '27c401da',
    'container.build_time' => 1522579022,
));
